
AWSTemplateFormatVersion: '2010-09-09'

Description:  Two Private PROD Subnets with default route to NGW, and Dynamic routing over VPN to campus.

Resources:
  AppAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: vpc-a1ddf0d9
      CidrBlock: 10.28.137.64/27
      AvailabilityZone: "us-east-1a"
      MapPublicIpOnLaunch: False
      Tags:
      - Key: Name
        Value: lambda-prod-rp-PvtAZ1
      - Key: Application
        Value: Researcher Portal 
      - Key: Environment
        Value: PROD
      - Key: Owner
        Value: awscloudops@northwestern.edu
  AppAZ1RT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: vpc-a1ddf0d9
      Tags:
      - Key: Name
        Value: lambda-prod-rp-PvtAZ1RT
      - Key: Application
        Value: Researcher Portal
      - Key: Environment
        Value: PROD
      - Key: Owner
        Value: awscloudops@northwestern.edu
    DependsOn:
      - AppAZ1
  AppAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: vpc-a1ddf0d9
      CidrBlock: 10.28.137.96/27
      AvailabilityZone: "us-east-1b"
      MapPublicIpOnLaunch: False
      Tags:
      - Key: Name
        Value: lambda-prod-rp-PvtAZ2
      - Key: Application
        Value: Researcher Portal
      - Key: Environment
        Value: PROD
      - Key: Owner
        Value: awscloudops@northwestern.edu
  AppAZ2RT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: vpc-a1ddf0d9
      Tags:
      - Key: Name
        Value: lambda-prod-rp-PvtAZ2RT
      - Key: Application
        Value: Researcher Portal
      - Key: Environment
        Value: PROD
      - Key: Owner
        Value: awscloudops@northwestern.edu
    DependsOn:
      - AppAZ2
  AppAZ1RTAssoc:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref AppAZ1RT
      SubnetId: !Ref AppAZ1
  AppAZ1Route:
    Type: "AWS::EC2::Route"
    Properties:  
        DestinationCidrBlock: 0.0.0.0/0
        NatGatewayId: nat-0b0cffb36f82064ba
        RouteTableId: !Ref AppAZ1RT
  AppAZ2RTAssoc:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref AppAZ2RT
      SubnetId: !Ref AppAZ2
  AppAZ2Route:
    Type: 'AWS::EC2::Route'
    Properties:  
        DestinationCidrBlock: 0.0.0.0/0
        NatGatewayId: nat-072392e99b6a47019
        RouteTableId: !Ref AppAZ2RT
  VGWprop:
    Type: 'AWS::EC2::VPNGatewayRoutePropagation'
    Properties:
        RouteTableIds: 
        - !Ref AppAZ1RT
        - !Ref AppAZ2RT
        VpnGatewayId: vgw-2938cc40
    DependsOn:
      - AppAZ1